FROM node:20-alpine
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY packages/contracts/package.json ./packages/contracts/package.json
COPY integrations/mock-coffee-time/package.json ./integrations/mock-coffee-time/package.json
RUN pnpm install --filter @zayuno/mock-coffee-time... --frozen-lockfile
COPY packages/contracts ./packages/contracts
COPY integrations/mock-coffee-time ./integrations/mock-coffee-time
RUN pnpm --filter @zayuno/contracts run build
RUN pnpm --filter @zayuno/mock-coffee-time run build
EXPOSE 4005
CMD ["node", "integrations/mock-coffee-time/dist/index.js"]
