FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g pnpm@9.15.0 turbo

COPY package.json pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY packages ./packages
COPY apps/worker ./apps/worker

RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @zayuno/database run generate
RUN pnpm --filter "./packages/*" run build
RUN pnpm --filter @zayuno/worker run build

CMD ["node", "apps/worker/dist/index.js"]
