import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
const widget = readFileSync(new URL('../dist/ui/text-choices.html', import.meta.url), 'utf8');
const html = `<!doctype html><html lang="uz"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Zayuno · Text choices preview</title>
<style>*{box-sizing:border-box}body{margin:0;background:#171819;color:#eee;font:15px system-ui,sans-serif}body.light{background:#fff;color:#202123}main{max-width:720px;margin:56px auto;padding:0 24px}header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:48px}.brand{font-size:15px;font-weight:650;letter-spacing:2px}.tag{font-size:11px;letter-spacing:0;color:#93979f;font-weight:400;margin-top:6px}button{font:inherit;font-size:12px;color:inherit;border:1px solid #60636b;background:transparent;border-radius:20px;padding:8px 14px;cursor:pointer}.user{margin:20px 0 28px auto;padding:14px 19px;border-radius:22px;max-width:85%;width:fit-content;background:#2d2f33}.light .user{background:#f0f1f4}.assistant{display:flex;gap:12px}.mark{width:26px;height:26px;margin-top:20px;border-radius:50%;border:1px solid #646872;display:grid;place-items:center;font-size:11px}iframe{display:block;flex:1;min-width:0;border:0;width:100%;height:340px}#messages{color:#969ba5;font-size:13px;line-height:1.5}.note{margin-top:38px;padding-top:16px;border-top:1px solid #36383c;color:#969ba5;font-size:12px;line-height:1.7}@media(max-width:440px){main{margin-top:24px;padding:0 12px}.assistant{gap:4px}.mark{display:none}}</style>
<main><header><div class="brand">ZAYUNO<div class="tag">Chat ichidagi tanlovlar · prototip</div></div><div><button id="reset">Boshidan</button> <button id="theme">Yorug‘ rejim</button></div></header><div class="user">Menga fast food kerak</div><div class="assistant"><span class="mark">Z</span><iframe title="Zayuno tanlovlari" src="/widget"></iframe></div><p id="messages" role="status"></p><p class="note">Sinov namunalari. Narxlar haqiqiy katalogdan olinmagan; buyurtma yaratilmaydi.<br>Bu sahifa chat hostini taqlid qiladi. ChatGPT ichidagi ishlashini alohida tekshirish kerak.</p></main>
<script>
const frame=document.querySelector('iframe');let theme='dark',stage='providers';
const providers={kind:'providers',title:'Qaysi servisdan buyurtma qilamiz?',subtitle:'Sevimli taomingiz shu yerdan boshlanadi.',items:[
  {id:'evos',label:'EVOS',prompt:'EVOS katalogini ko‘rsat',imageUrl:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=160&auto=format&fit=crop&q=80'},
  {id:'oqtepa',label:'Oqtepa Lavash',prompt:'Oqtepa Lavash katalogini ko‘rsat',imageUrl:'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=160&auto=format&fit=crop&q=80'},
  {id:'bellissimo',label:'Bellissimo Pizza',prompt:'Bellissimo Pizza katalogini ko‘rsat',imageUrl:'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=160&auto=format&fit=crop&q=80'}
]};
const products=name=>({kind:'products',title:'Nima tanlaymiz?',subtitle:name+' · Taomni tanlang',items:[
  {id:'1',label:'Katta mol go‘shtli lavash',price:34000,currency:'UZS',category:'Lavashlar',imageUrl:'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=160&auto=format&fit=crop&q=80',prompt:name+' menyusidan Katta mol go‘shtli lavash tanlayman. Variantlarini ko‘rsat.'},
  {id:'2',label:'Pishloqli lavash',price:38000,currency:'UZS',category:'Lavashlar',imageUrl:'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=160&auto=format&fit=crop&q=80',prompt:name+' menyusidan Pishloqli lavash tanlayman. Variantlarini ko‘rsat.'},
  {id:'3',label:'Pepperoni pitsa',price:55000,currency:'UZS',category:'Pitsa',imageUrl:'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=160&auto=format&fit=crop&q=80',prompt:name+' menyusidan Pepperoni pitsa tanlayman. Variantlarini ko‘rsat.'},
  {id:'4',label:'Chizburger',price:29000,currency:'UZS',category:'Burgerlar',imageUrl:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=160&auto=format&fit=crop&q=80',prompt:name+' menyusidan Chizburger tanlayman. Variantlarini ko‘rsat.'},
  {id:'5',label:'Mini lavash',price:28000,currency:'UZS',category:'Lavashlar',imageUrl:'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=160&auto=format&fit=crop&q=80',prompt:name+' menyusidan Mini lavash tanlayman. Variantlarini ko‘rsat.'},
  {id:'6',label:'Coca-Cola 0.5 L',price:9000,currency:'UZS',category:'Ichimliklar',imageUrl:'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=160&auto=format&fit=crop&q=80',prompt:name+' menyusidan Coca-Cola 0.5 L tanlayman. Variantlarini ko‘rsat.'}
]});
let current=providers;const post=message=>frame.contentWindow.postMessage({jsonrpc:'2.0',...message},location.origin);const render=()=>post({method:'ui/notifications/tool-result',params:{content:[],_meta:{zayunoChoices:current}}});
window.addEventListener('message',event=>{if(event.source!==frame.contentWindow||event.origin!==location.origin)return;const m=event.data;if(m.method==='ui/initialize')post({id:m.id,result:{protocolVersion:m.params.protocolVersion,hostInfo:{name:'Local preview',version:'1.0'},hostCapabilities:{message:{text:{}}},hostContext:{theme,displayMode:'inline',availableDisplayModes:['inline']}}});if(m.method==='ui/notifications/initialized')render();if(m.method==='ui/notifications/size-changed')frame.style.height=m.params.height+'px';if(m.method==='ui/message'){post({id:m.id,result:{}});const text=m.params.content[0].text;document.getElementById('messages').textContent='Chatga yuborildi: '+text;if(stage==='providers'){stage='products';current=products(text.replace(' katalogini ko‘rsat',''));setTimeout(render,300)}}});
document.getElementById('reset').onclick=()=>{stage='providers';current=providers;document.getElementById('messages').textContent='';render()};document.getElementById('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';document.body.classList.toggle('light',theme==='light');document.getElementById('theme').textContent=theme==='dark'?'Yorug‘ rejim':'Qorong‘i rejim';post({method:'ui/notifications/host-context-changed',params:{theme}})};
</script></html>`;
createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');const liveWidget=readFileSync(new URL('../dist/ui/text-choices.html', import.meta.url), 'utf8');res.end(req.url==='/widget'?liveWidget:html)}).listen(4318,'127.0.0.1',()=>console.log('Preview: http://127.0.0.1:4318'));
